import { simpleDate, MuaphungSinh } from './commonData';
export declare const tinhngayramsau21thang3: (y: number) => simpleDate;
export declare function tinhThuTuLeTro(ngayLePhucSinh: Date): Date;
export declare const tinhNgayPhucSinh: (year: number) => Date | false;
export declare function tinhLeChuaHienLinh(y: number): Date;
export declare function tinhLeThanhGia(y: number): Date;
export declare function tinhLeChuaChiuPhepRua(y: number): Date | false;
export declare const tinhLeChuaKiToVua: (chuaNhatThuNhatMuaVong: Date) => Date;
export declare const tinhLeChuaThanhThanHienxuong: (easter: Date) => Date;
export declare const tinhLeChuaBaNgoi: (leChuaThanhThanHienXuong: Date) => Date;
export declare const tinhLeMinhMauThanhChua: (tinhLeChuaBaNgoi: Date) => Date;
export declare const tinhLeThanhTamChuaGieSu: (tinhLeMinhMauThanhChua: Date) => Date;
export declare const tinhChuaNhatThuongNienDauTienSauLeChuaThanhThanHienXuong: (leKiToVua: Date, leChuatthienxuong: Date) => number;
export declare function tinhNamABC(y: number): string;
export declare function tinh4TuanMuaVong(y: number): MuaphungSinh;
export declare const firstSundayOfLent: (ashWednesday: Date) => Date;
export declare const secondSundayOfLent: (ashWednesday: Date) => Date;
export declare const thirdSundayOfLent: (ashWednesday: Date) => Date;
export declare const fourthSundayOfLent: (ashWednesday: Date) => Date;
export declare const fifthSundayOfLent: (ashWednesday: Date) => Date;
export declare const calculateTheAscentionOfTheLord: (easter: Date) => Date;
export declare const palmSunday: (ashWednesday: Date) => Date;
